/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.index;

import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpExchange;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;

public class App
{

    public static void main(String[] args)
    {
	try {
	    HttpServer srv = HttpServer.create(new InetSocketAddress(8080), 0);
	    srv.createContext("/", new index());

	    srv.setExecutor(null);
	    srv.start();
	} catch (IOException e) {
	    System.out.println("error starting server: " + e.getMessage());

	}
    }
}

